name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
          # create JAR file with maven and run the package
      - name: Create the JAR file with Maven
        run: mvn package
        
        
      # Install Node.js 
      - name: set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Install newman
      - name: Install newman
        run: | 
         npm install -g newman
         npm install -g newman-reporter-htmlextra
         
      - name: Start applicatie
        run: nohup mvn spring-boot:run > /dev/null 2>&1 &
      - name: ff wachten
        run: sleep 10
         
      - name: Run Postman collections game
        run: newman run src/test/Game.postman_collection.json
      - name: Run Postman collections rider
        run: newman run src/test/Rider.postman_collection.json
      - name: Run Postman collections enrollment
        run: newman run src/test/Enrollment.postman_collection.json
         
         
        
        
