name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
        # create JAR file with maven and run the package
      - name: Create the JAR file with Maven
        run: mvn package -DskipTests
        
        #Run static code analyses
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@mast
        
        #Run Unit tests
      - name: Run Unit Test
        run: mvn test -Dgroups="UnitTest"
        
        #Run Integration tests
      - name: Run Integration Test
        run: mvn test -Dgroups="IntegrationTest"
        
      # Install newman
      - name: Install newman
        run: | 
         npm install -g newman
         npm install -g newman-reporter-htmlextra
         
      - name: Start applicatie
        run: nohup mvn spring-boot:run > /dev/null 2>&1 &
      - name: Wait 10 seconds so the application is ready
        run: sleep 10
         
      - name: Run Postman API collections game
        run: newman run src/test/Game.postman_collection.json
      - name: Run Postman API collections rider
        run: newman run src/test/Rider.postman_collection.json
      - name: Run Postman API collections enrollment
        run: newman run src/test/Enrollment.postman_collection.json
         
         
        
        
